# Generated by Django 6.0.5 on 2026-05-20 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('harga_jual', models.DecimalField(decimal_places=0, max_digits=12)),
                ('harga_beli', models.DecimalField(decimal_places=0, max_digits=12)),
                ('stok', models.IntegerField(default=0)),
                ('stok_minimum', models.IntegerField(default=5)),
                ('satuan', models.CharField(default='pcs', max_length=20)),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diubah', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.kategori')),
            ],
            options={
                'verbose_name_plural': 'Produk',
            },
        ),
    ]
