# Generated by Django 6.0.5 on 2026-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_alter_kategori_id_alter_produk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
