# Generated by Django 6.0.5 on 2026-05-20 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
        ('stok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piutang',
            name='pelanggan',
        ),
        migrations.RemoveField(
            model_name='pembayaranpiutang',
            name='piutang',
        ),
        migrations.RemoveField(
            model_name='piutang',
            name='transaksi',
        ),
        migrations.CreateModel(
            name='StokMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('harga_beli', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True)),
                ('dicatat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.produk')),
            ],
            options={
                'verbose_name_plural': 'Stok Masuk',
            },
        ),
        migrations.DeleteModel(
            name='Pelanggan',
        ),
        migrations.DeleteModel(
            name='PembayaranPiutang',
        ),
        migrations.DeleteModel(
            name='Piutang',
        ),
    ]
