# Generated by Django 5.1.2 on 2026-05-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0002_remove_piutang_pelanggan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokmasuk',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
