# Generated by Django 6.0.5 on 2026-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0003_alter_stokmasuk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokmasuk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
