# Generated by Django 5.1.2 on 2026-05-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransaksi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='metode_bayar',
            field=models.CharField(choices=[('tunai', 'Tunai'), ('transfer', 'Transfer'), ('qris', 'QRIS'), ('piutang', 'Piutang')], default='tunai', max_length=20),
        ),
    ]
