# Generated by Django 6.0.5 on 2026-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0002_alter_detailtransaksi_id_alter_transaksi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='alasan_batal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('selesai', 'Selesai'), ('batal', 'Dibatalkan')], default='selesai', max_length=10),
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
