# Generated by Django 6.0.5 on 2026-05-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kasir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('dibuat', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Piutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('terbayar', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('belum', 'Belum Lunas'), ('sebagian', 'Sebagian'), ('lunas', 'Lunas')], default='belum', max_length=10)),
                ('jatuh_tempo', models.DateField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piutang.pelanggan')),
                ('transaksi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.transaksi')),
            ],
            options={
                'verbose_name_plural': 'Piutang',
            },
        ),
        migrations.CreateModel(
            name='PembayaranPiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True)),
                ('piutang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='piutang.piutang')),
            ],
        ),
    ]
