# Generated by Django 6.0.5 on 2026-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piutang', '0002_alter_pelanggan_id_alter_pembayaranpiutang_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pembayaranpiutang',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='piutang',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
